# Extend the existing Node.js & TypeScript image
FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Set environment variables to avoid interaction during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install ffmpeg and default JRE
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    default-jre \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    # npm install --global gulp-cli

# Install Python
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    pip install --no-cache-dir --break-system-packages tensorflow-aarch64 keras Flask Flask-Cors

# Check CPU architecture and install the appropriate version of TensorFlow
# RUN CPU_ARCH=$(uname -m) && \
#     if [[ "$CPU_ARCH" == "x86_64" ]]; then \
#         pip install tensorflow==2.12.0; \
#     elif [[ "$CPU_ARCH" == "aarch64" ]]; then \
#         pip install tensorflow-aarch64==2.12.0; \
#     elif [[ "$CPU_ARCH" == "ARM64" ]]; then \
#         pip install tensorflow-aarch64==2.12.0; \
#     else \
#         echo "Unsupported architecture: $CPU_ARCH"; \
#         exit 1; \
#     fi